# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measure',
            new_name='Lecture',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='measure',
            new_name='lecture',
        ),
    ]
