# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20160906_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='day',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='day',
            field=models.DateField(unique=True),
        ),
    ]
